name: primeirojeto
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.2
  flutter_pw_validator: ^1.6.0
  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/monalsa.jpeg
    - assets/images/meninosA.jpeg
    - assets/images/indiomulata.jpeg
